#!/bin/bash

git config --global user.name "Dominik Tarnowski"
git config --global user.email "dom@tdom.dev"

if ! [ -x "$(command -v yay)" ]; then
  git clone https://aur.archlinux.org/yay.git
  cd yay
  makepkg -si
  cd ..
  rm -rf yay
fi

yay -S neovim zsh nerd-fonts-fira-code code stow noto-fonts-emoji

sudo systemctl enable systemd-timesyncd.service
timedatectl set-ntp true

# oh my zsh (zsh)
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# vim plug (neovim)
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# extensions (code)
cat .code-extensions | xargs -L 1 code --install-extension
